//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTechArt.Shop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buye
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public double Count { get; set; }
        public int OrderId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Order Order { get; set; }
    }
}
